export enum KycStatus {
  PENDING = 'PENDING',
  DOCUMENTS_REQUESTED = 'DOCUMENTS_REQUESTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  ENHANCED_DUE_DILIGENCE = 'ENHANCED_DUE_DILIGENCE',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export const KYC_TERMINAL_STATUSES: KycStatus[] = [KycStatus.APPROVED, KycStatus.REJECTED];
